### ISSUE TITLE
"/components/jquery/jquery.js does not exist", assetic:dump with components errors

### ISSUE THREAD

**Issue by Hakadel** [symfony2admingenerator/AdmingeneratorGeneratorBundle#654]
Hello,

I have a problem with the "php app/console assetic:dump" command :

```
The source file "/home/me/public_html/client/app/../web/components/jquery/jquery.js" does not exist.
```

But in "vendor/components/jquery" the "jquery.js" file exist...

Any idea ?

Thanks.

**Comment by wolfdogg** [comment]
having this issue...  `The source file "/app/../web/./vendor/jquery/jquery/jquery-1.11.2.js" does not exist.`

**Comment by loostro** [comment]
Try `cache clear` before `assetic:dump`
