### ISSUE TITLE
GenerateAdminCommand compatible with SensioGeneratorBundle

### ISSUE THREAD

**Issue by kadryjanek** [symfony2admingenerator/AdmingeneratorGeneratorBundle#819]
After installing <code>AdmingeneratorGeneratorBundle</code> in <code>Symfony 2.6.1</code> project in <code>SensioGeneratorBundle</code> i got error:
<pre>
Runtime Notice: Declaration of Admingenerator\GeneratorBundle\Command\GenerateAdminCommand::updateRouting() should be compatible with Sensio\Bundle\GeneratorBundle\Command\GenerateBundleCommand::updateRouting(Sensio\Bundle\GeneratorBundle\Command\Helper\QuestionHelper $questionHelper, Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output, $bundle, $format) h
</pre>

This is related to: https://github.com/sensiolabs/SensioGeneratorBundle/commit/59eebd0d067cfbc8d12e509a44cb44f8eea4739a

This change was introduced to versions: 2.5.X, 2.4.X, 2.3.X.

**Comment by sescandell** [comment]
Hi @kadryjanek 

Take a look to the following workaround waiting for some future resolution: https://github.com/symfony2admingenerator/GeneratorBundle/issues/54#issuecomment-66536365

**Comment by kadryjanek** [comment]
Ok, Thx!
