### ISSUE TITLE
Conflict with avocode/form-extensions-bundle

### ISSUE THREAD

**Issue by crash21** [symfony2admingenerator/AdmingeneratorGeneratorBundle#828]
Hello,

Latest avocode/form-extensions-bundle needs install twig/extensions v1.2.0 but this bundle is still on v1.0.0.

I get this error:

  Problem 1
    - Installation request for symfony/framework-standard-edition 2.6.x-dev -> satisfiable by symfony/framework-standard-edition[2.6.x-dev].
    - symfony/framework-standard-edition 2.6.x-dev requires avocode/form-extensions-bundle dev-master -> satisfiable by avocode/form-extensions-bundle[dev-master].
    - avocode/form-extensions-bundle dev-master requires twig/extensions ~1.2 -> satisfiable by twig/extensions[v1.2.0].
    - avocode/form-extensions-bundle dev-master requires twig/extensions ~1.2 -> satisfiable by twig/extensions[v1.2.0].
    - Conclusion: don't install twig/extensions v1.2.0

Please let me know if its a bug or i do something wrong.

**Comment by loostro** [comment]
@sescandell do you recall any reason why this bundle is locked on twig extensions `v1.0.*` ?

**Comment by sescandell** [comment]
@loostro I think this is just an error, and correct restriction can be moved to `~1.0` 

@crash21 could you provide a PR please ?

**Comment by crash21** [comment]
Hello,

Sure I can do it, in which branch?

**Comment by sescandell** [comment]
Starting from v1.0

**Comment by crash21** [comment]
Done https://github.com/symfony2admingenerator/AdmingeneratorGeneratorBundle/pull/831

**Comment by ioleo** [comment]
added to 1.1 and master
