### ISSUE TITLE
Add uglifyjs and uglifycss support

### ISSUE THREAD

**Issue by ndoulgeridis** [symfony2admingenerator/AdmingeneratorGeneratorBundle#834]
Hello,

Currently there is only yui_css and yui_js support. Is it possible to add support also for uglifycss and uglifyjs? Can you please give me some guidelines so I can try do it myself and then push?

Thanks a lot.

**Comment by ioleo** [comment]
@crash21 

1) create new base template, that extends [base_admin.html.twig](https://github.com/symfony2admingenerator/AdmingeneratorGeneratorBundle/blob/master/Resources/views/base_admin.html.twig)

2) overwrite the scripts_head, stylesheets and javascripts blocks (change the filters to uglifyjs/css)

3) change the `'admingenerator.base_admin_template` configuration parameter to your new base template

**Comment by ndoulgeridis** [comment]
Hello,

Would it be better maybe to have the filter selectable via an option in config? So have available both yui and uglify and default yui.

**Comment by ioleo** [comment]
No, I think overwriteing the base template is easy enough (and flexible enough), we do not need a seperate config param for this.
