### ISSUE TITLE
Global stopOnFail(true) should be overrideable with local stopOnFail

### ISSUE THREAD

**Issue by c33s** [symfony2admingenerator/AdmingeneratorGeneratorBundle#839]
having set the global `stopOnFail()` to `false` should be overrideable

```
/**
 * RoboFile constructor.
 */
public function __construct()
{
    $this->stopOnFail(true);
}
```

the `stopOnFail(false)` in the `taskExecStack()` doesn't prevent the stop.

```
$this->taskExecStack()
    ->stopOnFail(false)
    ->exec('my failing command')
    ->run();
```

**Comment by bobvandevijver** [comment]
I guess you wanted to post this at another repo (https://github.com/Codegyre/Robo) and not here.

**Comment by c33s** [comment]
sorry, had to many github tabs open :)
