### ISSUE TITLE
updateRouting() should be compatible

### ISSUE THREAD

**Issue by bradInside** [symfony2admingenerator/AdmingeneratorGeneratorBundle#840]
i had issue getting this notice when installing with composer :
`Runtime Notice: Declaration of Admingenerator\GeneratorBundle\Command\GenerateAdminAdminCommand::updateRouting() should be compatible with Sensio\Bundle\GeneratorBundle\C          
  ommand\GenerateBundleCommand::updateRouting(Sensio\Bundle\GeneratorBundle\Command\Helper\QuestionHelper $questionHelper, Symfony\Component\Console\Input\InputInterface $input, Symf  
  ony\Component\Console\Output\OutputInterface $output, $bundle, $format)`

i fixed it putting the "sensio/generator-bundle" to 2.4 in composer 
( the last release is 2.5 right now  and not compatible )

**Comment by bobvandevijver** [comment]
This is the legacy bundle, which is no longer updated. Please update to the [new bundle](https://github.com/symfony2admingenerator/GeneratorBundle) (it also has a complete documentation :))
